import {
  BedDouble,
  Bell,
  CalendarCheck,
  Camera,
  FileImage,
  FilePlus2,
  FileText,
  Globe2,
  Images,
  Inbox,
  LayoutDashboard,
  ListTree,
  Map,
  MapPinned,
  PackagePlus,
  Plane,
  Settings,
  Tags,
  Trash2,
  Newspaper,
} from "lucide-react";
import type { ComponentType } from "react";

type Icon = ComponentType<{ size?: number; strokeWidth?: number }>;

export type PortalField =
  | { label: string; name: string; required?: boolean; rows?: number; type: "content" | "textarea" }
  | { itemName?: string; label: string; name: string; required?: boolean; rows?: number; type: "list" | "qa-list" }
  | { label: string; name: string; required?: boolean; type: "checkbox" | "date" | "email" | "number" | "text" | "url" }
  | { label: string; name: string; options: Array<{ label: string; value: string }>; required?: boolean; type: "select" }
  | { hasMany?: boolean; label: string; name: string; relationTo: string; required?: boolean; type: "relationship" };

export type PortalModule = {
  collection?: string;
  description: string;
  editModuleSlug?: string;
  emptyLabel: string;
  fields: PortalField[];
  global?: string;
  href: string;
  icon: Icon;
  label: string;
  listWhere?: Record<string, unknown>;
  navLabel: string;
  newLabel?: string;
  tableColumns: Array<{ key: string; label: string }>;
  trashable?: boolean;
  trashView?: boolean;
};

export type SidebarLink = {
  href: string;
  icon: Icon;
  label: string;
};

export type SidebarGroup = {
  defaultOpen?: boolean;
  icon: Icon;
  label: string;
  links: SidebarLink[];
};

const statusOptions = [
  { label: "Draft", value: "draft" },
  { label: "Published", value: "published" },
  { label: "Trashed", value: "trashed" },
];

const postStatusOptions = statusOptions;

const availabilityOptions = [
  { label: "Available", value: "available" },
  { label: "Limited", value: "limited" },
  { label: "Unavailable", value: "unavailable" },
  { label: "On Request", value: "on-request" },
];

const seoFields: PortalField[] = [
  { label: "SEO title", name: "metaTitle", type: "text" },
  { label: "SEO description", name: "metaDescription", rows: 3, type: "textarea" },
  { label: "SEO keywords", name: "keywords", type: "text" },
  { label: "Canonical slug", name: "canonicalSlug", type: "text" },
];

export const portalModules: Record<string, PortalModule> = {
  navigation: {
    collection: "navigation-items",
    description: "Manage public menu links.",
    emptyLabel: "No navigation items yet.",
    fields: [
      { label: "Label", name: "label", required: true, type: "text" },
      { label: "Dropdown group", name: "parentLabel", type: "text" },
      { label: "Link type", name: "linkType", options: [
        { label: "Custom URL / static page", value: "custom-url" },
        { label: "Destination", value: "destination" },
        { label: "Trip", value: "trip" },
        { label: "Package", value: "package" },
      ], type: "select" },
      { label: "Custom URL", name: "customUrl", type: "text" },
      { label: "Destination", name: "destination", relationTo: "destinations", type: "relationship" },
      { label: "Trip", name: "trip", relationTo: "trips", type: "relationship" },
      { label: "Package", name: "package", relationTo: "packages", type: "relationship" },
      { label: "Sort order", name: "sortOrder", type: "number" },
      { label: "Visible", name: "visible", type: "checkbox" },
      { label: "Primary button", name: "isPrimaryAction", type: "checkbox" },
      { label: "Notes", name: "notes", rows: 3, type: "textarea" },
    ],
    href: "/admin/navigation",
    icon: ListTree,
    label: "Navigation",
    navLabel: "Navigation",
    newLabel: "New menu item",
    tableColumns: [
      { key: "label", label: "Label" },
      { key: "parentLabel", label: "Group" },
      { key: "linkType", label: "Type" },
      { key: "sortOrder", label: "Order" },
      { key: "visible", label: "Visible" },
    ],
  },
  trips: {
    collection: "trips",
    description: "Manage safari trips.",
    emptyLabel: "No trips yet.",
    fields: [
      { label: "Trip title", name: "title", required: true, type: "text" },
      { label: "Slug", name: "slug", required: true, type: "text" },
      { label: "Destinations", name: "destinations", relationTo: "destinations", hasMany: true, type: "relationship" },
      { label: "Location", name: "location", type: "text" },
      { label: "Days", name: "days", type: "number" },
      { label: "Nights", name: "nights", type: "number" },
      { label: "Package", name: "package", relationTo: "packages", type: "relationship" },
      { label: "Itinerary days", name: "itineraryDaysJson", rows: 14, type: "content" },
      { label: "Status", name: "status", options: [...statusOptions, { label: "Paused", value: "paused" }, { label: "Sold Out", value: "sold-out" }], type: "select" },
      { label: "Start date", name: "startDate", type: "date" },
      { label: "End date", name: "endDate", type: "date" },
      { label: "Availability", name: "availability", options: availabilityOptions, type: "select" },
      { label: "Budget currency", name: "budget.currency", type: "text" },
      { label: "Budget min", name: "budget.min", type: "number" },
      { label: "Budget max", name: "budget.max", type: "number" },
      { label: "Budget display", name: "budget.displayText", type: "text" },
      { label: "Carousel media", name: "galleryImages", relationTo: "media", hasMany: true, type: "relationship" },
      { label: "Carousel alt text", name: "galleryAltText", rows: 5, type: "list" },
      { label: "Carousel captions", name: "galleryCaptions", itemName: "caption", rows: 5, type: "list" },
      { label: "Trip overview", name: "overview", rows: 8, type: "content" },
      { label: "Included", name: "includedItems", itemName: "item", rows: 7, type: "list" },
      { label: "Excluded", name: "excludedItems", itemName: "item", rows: 7, type: "list" },
      { label: "Map embed URL", name: "mapEmbedUrl", type: "url" },
      { label: "Latitude", name: "latitude", type: "text" },
      { label: "Longitude", name: "longitude", type: "text" },
      { label: "Discount enabled", name: "discount.enabled", type: "checkbox" },
      { label: "Discount label", name: "discount.label", type: "text" },
      { label: "Discount amount", name: "discount.amountText", type: "text" },
      { label: "Featured", name: "featured", type: "checkbox" },
      { label: "Notes", name: "notes", rows: 4, type: "textarea" },
      { label: "FAQs", name: "faqsJson", rows: 10, type: "qa-list" },
      { label: "Direct answers", name: "directAnswersJson", rows: 10, type: "qa-list" },
      { label: "SEO title", name: "seo.title", type: "text" },
      { label: "SEO description", name: "seo.description", rows: 3, type: "textarea" },
      { label: "SEO keywords", name: "seo.keywords", type: "text" },
      { label: "Canonical slug", name: "seo.canonicalSlug", type: "text" },
    ],
    href: "/admin/trips",
    icon: Tags,
    label: "All Trips",
    navLabel: "All Trips",
    newLabel: "New trip",
    tableColumns: [
      { key: "title", label: "Trip" },
      { key: "status", label: "Status" },
      { key: "startDate", label: "Start" },
      { key: "availability", label: "Availability" },
      { key: "budget.displayText", label: "Budget" },
    ],
    trashable: true,
  },
  packages: {
    collection: "packages",
    description: "Edit safari products.",
    emptyLabel: "No packages yet.",
    fields: [
      { label: "Package title", name: "title", required: true, type: "text" },
      { label: "Slug", name: "slug", required: true, type: "text" },
      { label: "Status", name: "status", options: statusOptions, type: "select" },
      { label: "Category", name: "category", options: [
        { label: "Kenya Safaris", value: "Kenya Safaris" },
        { label: "Tanzania Safaris", value: "Tanzania Safaris" },
        { label: "Kenya Tanzania Combined", value: "Kenya Tanzania Combined Safaris" },
        { label: "Kenya Adventure", value: "Kenya Adventure Safaris" },
        { label: "Tanzania Adventure", value: "Tanzania Adventure Safaris" },
      ], required: true, type: "select" },
      { label: "Package group", name: "packageGroup", options: [
        { label: "Mount Kenya Climbing", value: "mount-kenya-climbing" },
        { label: "Nairobi Excursion", value: "nairobi-excursion" },
        { label: "Day Trips", value: "day-trips" },
        { label: "Economy Private Safaris", value: "economy-private" },
        { label: "Group Joining Safaris", value: "group-joining" },
        { label: "Kenya Lodge Safaris", value: "kenya-lodge" },
        { label: "Kenya Fly In Safaris", value: "kenya-fly-in" },
        { label: "Beach Extension", value: "beach-extension" },
        { label: "4x4 Safaris", value: "4x4-safaris" },
        { label: "Short Safaris", value: "short-safaris" },
        { label: "Mount Kilimanjaro Climbing", value: "kilimanjaro-climbing" },
        { label: "Tanzania Lodge Safaris", value: "tanzania-lodge" },
        { label: "Tanzania Budget Camping Safaris", value: "tanzania-budget-camping" },
        { label: "Kenya & Tanzania Lodge Safaris", value: "combined-lodge" },
        { label: "Private Economy Safaris", value: "combined-private-economy" },
        { label: "Combined Group Joining Safaris", value: "combined-group-joining" },
        { label: "Combined Lodge Safari", value: "combined-lodge-safari" },
        { label: "Combined Budget Safari", value: "combined-budget" },
      ], type: "select" },
      { label: "Duration", name: "duration", type: "text" },
      { label: "Price text", name: "priceText", type: "text" },
      { label: "Featured", name: "featured", type: "checkbox" },
      { label: "Excerpt", name: "excerpt", required: true, rows: 4, type: "textarea" },
      { label: "Content", name: "content", rows: 12, type: "content" },
      { label: "Destinations text", name: "destinationsText", type: "text" },
      { label: "Destinations", name: "destinations", relationTo: "destinations", hasMany: true, type: "relationship" },
      { label: "Itinerary", name: "itinerary", relationTo: "itineraries", type: "relationship" },
      { label: "Best time", name: "bestTime", type: "text" },
      { label: "Discount enabled", name: "discount.enabled", type: "checkbox" },
      { label: "Discount label", name: "discount.label", type: "text" },
      { label: "Discount amount", name: "discount.amountText", type: "text" },
      ...seoFields,
    ],
    href: "/admin/packages",
    icon: PackagePlus,
    label: "Packages",
    navLabel: "Packages",
    newLabel: "New package",
    tableColumns: [
      { key: "title", label: "Package" },
      { key: "category", label: "Category" },
      { key: "packageGroup", label: "Group" },
      { key: "status", label: "Status" },
      { key: "priceText", label: "Price" },
      { key: "featured", label: "Featured" },
    ],
    trashable: true,
  },
  destinations: {
    collection: "destinations",
    description: "Manage destination pages.",
    emptyLabel: "No destinations yet.",
    fields: [
      { label: "Name", name: "name", required: true, type: "text" },
      { label: "Slug", name: "slug", required: true, type: "text" },
      { label: "Status", name: "status", options: statusOptions, type: "select" },
      { label: "Country", name: "country", options: [{ label: "Kenya", value: "kenya" }, { label: "Tanzania", value: "tanzania" }], required: true, type: "select" },
      { label: "Region", name: "region", type: "text" },
      { label: "Hero image", name: "heroImage", relationTo: "media", type: "relationship" },
      { label: "Summary", name: "summary", required: true, rows: 4, type: "textarea" },
      { label: "Content", name: "content", rows: 12, type: "content" },
      { label: "Gallery media", name: "galleryImages", relationTo: "media", hasMany: true, type: "relationship" },
      { label: "Gallery alt text", name: "galleryAltText", rows: 5, type: "list" },
      { label: "Gallery captions", name: "galleryCaptions", itemName: "caption", rows: 5, type: "list" },
      { label: "Map embed URL", name: "mapEmbedUrl", type: "url" },
      { label: "Latitude", name: "latitude", type: "text" },
      { label: "Longitude", name: "longitude", type: "text" },
      { label: "FAQs", name: "faqsJson", rows: 10, type: "qa-list" },
      { label: "Direct answers", name: "directAnswersJson", rows: 10, type: "qa-list" },
      { label: "SEO title", name: "seo.title", type: "text" },
      { label: "SEO description", name: "seo.description", rows: 3, type: "textarea" },
      { label: "SEO keywords", name: "seo.keywords", type: "text" },
      { label: "Canonical slug", name: "seo.canonicalSlug", type: "text" },
    ],
    href: "/admin/destinations",
    icon: MapPinned,
    label: "Destinations",
    navLabel: "Destinations",
    newLabel: "New destination",
    tableColumns: [
      { key: "name", label: "Destination" },
      { key: "status", label: "Status" },
      { key: "country", label: "Country" },
      { key: "region", label: "Region" },
      { key: "slug", label: "Slug" },
    ],
    trashable: true,
  },
  itineraries: {
    collection: "itineraries",
    description: "Build day plans.",
    emptyLabel: "No itineraries yet.",
    fields: [
      { label: "Title", name: "title", required: true, type: "text" },
      { label: "Package", name: "package", relationTo: "packages", type: "relationship" },
      { label: "Trip", name: "trip", relationTo: "trips", type: "relationship" },
      { label: "Number of days", name: "dayCount", type: "number" },
      { label: "Day plan", name: "daysJson", rows: 14, type: "content" },
    ],
    href: "/admin/itineraries",
    icon: Map,
    label: "Itineraries",
    navLabel: "Itineraries",
    newLabel: "New itinerary",
    tableColumns: [
      { key: "title", label: "Itinerary" },
      { key: "package", label: "Package" },
      { key: "dayCount", label: "Days" },
      { key: "updatedAt", label: "Updated" },
    ],
  },
  enquiries: {
    collection: "enquiries",
    description: "Review safari leads.",
    emptyLabel: "No enquiries yet.",
    fields: [
      { label: "Name", name: "name", required: true, type: "text" },
      { label: "Email", name: "email", required: true, type: "email" },
      { label: "Phone", name: "phone", type: "text" },
      { label: "Nationality", name: "nationality", type: "text" },
      { label: "Destination choice", name: "destinationChoice", type: "text" },
      { label: "Source trip", name: "sourceTrip", relationTo: "trips", type: "relationship" },
      { label: "Subject", name: "subject", type: "text" },
      { label: "Message", name: "message", required: true, rows: 5, type: "textarea" },
      { label: "Additional comments", name: "comments", rows: 5, type: "textarea" },
      { label: "Travel days", name: "travelDays", type: "text" },
      { label: "Tour start date", name: "tourStartDate", type: "date" },
      { label: "Preferred start date", name: "startDate", type: "date" },
      { label: "Preferred end date", name: "endDate", type: "date" },
      { label: "Flexible dates", name: "flexibleDates", type: "checkbox" },
      { label: "Adults", name: "adults", type: "text" },
      { label: "Children under 13", name: "children", type: "text" },
      { label: "Infants", name: "infants", type: "text" },
      { label: "Accommodation", name: "accommodationPreference", type: "text" },
      { label: "Budget range", name: "budgetRange", type: "text" },
      { label: "Budget per person", name: "budgetPerPerson", type: "text" },
      { label: "Planning stage", name: "planningStage", type: "text" },
      { label: "Trip type", name: "tripType", type: "text" },
      { label: "Referral source", name: "referralSource", type: "text" },
      { label: "Status", name: "status", options: [
        { label: "New", value: "new" },
        { label: "Contacted", value: "contacted" },
        { label: "Quoted", value: "quoted" },
        { label: "Booked", value: "booked" },
        { label: "Closed", value: "closed" },
      ], type: "select" },
      { label: "Notes", name: "internalNotes", rows: 5, type: "textarea" },
    ],
    href: "/admin/enquiries",
    icon: Inbox,
    label: "Enquiries",
    navLabel: "Enquiries",
    tableColumns: [
      { key: "name", label: "Lead" },
      { key: "destinationChoice", label: "Destination" },
      { key: "status", label: "Status" },
      { key: "planningStage", label: "Stage" },
      { key: "createdAt", label: "Received" },
    ],
  },
  bookings: {
    collection: "bookings",
    description: "Track booked safaris.",
    emptyLabel: "No bookings yet.",
    fields: [
      { label: "Traveller name", name: "travellerName", required: true, type: "text" },
      { label: "Traveller email", name: "travellerEmail", type: "email" },
      { label: "Traveller phone", name: "travellerPhone", type: "text" },
      { label: "Status", name: "status", options: [
        { label: "Lead", value: "lead" },
        { label: "Planning", value: "planning" },
        { label: "Quoted", value: "quoted" },
        { label: "Confirmed", value: "confirmed" },
        { label: "Completed", value: "completed" },
        { label: "Cancelled", value: "cancelled" },
      ], type: "select" },
      { label: "Package", name: "package", relationTo: "packages", type: "relationship" },
      { label: "Travel start", name: "travelStartDate", type: "date" },
      { label: "Travel end", name: "travelEndDate", type: "date" },
      { label: "Travellers", name: "travellers", type: "number" },
      { label: "Budget", name: "budgetText", type: "text" },
      { label: "Notes", name: "notes", rows: 5, type: "textarea" },
    ],
    href: "/admin/bookings",
    icon: CalendarCheck,
    label: "Bookings",
    navLabel: "Bookings",
    newLabel: "New booking",
    tableColumns: [
      { key: "travellerName", label: "Traveller" },
      { key: "status", label: "Status" },
      { key: "package", label: "Package" },
      { key: "travelStartDate", label: "Start" },
    ],
  },
  accommodations: {
    collection: "accommodations",
    description: "Manage stays.",
    emptyLabel: "No stays yet.",
    fields: [
      { label: "Name", name: "name", required: true, type: "text" },
      { label: "Type", name: "type", options: [
        { label: "Airbnb / Apartment", value: "airbnb" },
        { label: "Safari Lodge", value: "lodge" },
        { label: "Tented Camp", value: "camp" },
        { label: "Hotel", value: "hotel" },
      ], type: "select" },
      { label: "Location", name: "location", required: true, type: "text" },
      { label: "Price text", name: "priceText", type: "text" },
      { label: "Availability", name: "availability", options: availabilityOptions, type: "select" },
      { label: "Availability note", name: "availabilityNote", rows: 3, type: "textarea" },
      { label: "Description", name: "description", rows: 5, type: "textarea" },
    ],
    href: "/admin/accommodations",
    icon: BedDouble,
    label: "Accommodations",
    navLabel: "Accommodations",
    newLabel: "New stay",
    tableColumns: [
      { key: "name", label: "Stay" },
      { key: "location", label: "Location" },
      { key: "availability", label: "Availability" },
      { key: "priceText", label: "Price" },
    ],
  },
  posts: {
    collection: "posts",
    description: "Manage articles.",
    emptyLabel: "No articles yet.",
    fields: [
      { label: "Heading", name: "title", required: true, type: "text" },
      { label: "Slug", name: "slug", required: true, type: "text" },
      { label: "Status", name: "status", options: postStatusOptions, type: "select" },
      { label: "Category", name: "category", relationTo: "post-categories", type: "relationship" },
      { label: "Tags", name: "tags", relationTo: "article-tags", hasMany: true, type: "relationship" },
      { label: "Published at", name: "publishedAt", type: "date" },
      { label: "Featured", name: "featured", type: "checkbox" },
      { label: "Cover image", name: "image", relationTo: "media", type: "relationship" },
      { label: "Cover caption", name: "imageCaption", type: "text" },
      { label: "Excerpt", name: "excerpt", required: true, rows: 4, type: "textarea" },
      { label: "Article body", name: "body", required: true, rows: 16, type: "content" },
      ...seoFields,
    ],
    href: "/admin/posts",
    icon: Newspaper,
    label: "All Articles",
    navLabel: "All Articles",
    newLabel: "New article",
    tableColumns: [
      { key: "title", label: "Article" },
      { key: "status", label: "Status" },
      { key: "category", label: "Category" },
      { key: "publishedAt", label: "Published" },
    ],
    trashable: true,
  },
  "posts-trash": {
    collection: "posts",
    description: "Restore or delete articles.",
    editModuleSlug: "posts",
    emptyLabel: "Trash is empty.",
    fields: [],
    href: "/admin/posts-trash",
    icon: Trash2,
    label: "Trash",
    listWhere: { status: { equals: "trashed" } },
    navLabel: "Trash",
    tableColumns: [
      { key: "title", label: "Article" },
      { key: "category", label: "Category" },
      { key: "updatedAt", label: "Updated" },
    ],
    trashView: true,
  },
  "post-categories": {
    collection: "post-categories",
    description: "Manage article categories.",
    emptyLabel: "No categories yet.",
    fields: [
      { label: "Name", name: "name", required: true, type: "text" },
      { label: "Slug", name: "slug", required: true, type: "text" },
      { label: "Description", name: "description", rows: 4, type: "textarea" },
      { label: "SEO description", name: "seo.description", rows: 3, type: "textarea" },
      { label: "SEO keywords", name: "seo.keywords", type: "text" },
    ],
    href: "/admin/post-categories",
    icon: FileText,
    label: "Categories",
    navLabel: "Categories",
    newLabel: "New category",
    tableColumns: [
      { key: "name", label: "Category" },
      { key: "slug", label: "Slug" },
      { key: "description", label: "Description" },
    ],
  },
  "article-tags": {
    collection: "article-tags",
    description: "Manage article tags.",
    emptyLabel: "No tags yet.",
    fields: [
      { label: "Name", name: "name", required: true, type: "text" },
      { label: "Slug", name: "slug", required: true, type: "text" },
    ],
    href: "/admin/article-tags",
    icon: Tags,
    label: "Tags",
    navLabel: "Tags",
    newLabel: "New tag",
    tableColumns: [
      { key: "name", label: "Tag" },
      { key: "slug", label: "Slug" },
    ],
  },
  gallery: {
    collection: "gallery",
    description: "Curate gallery images.",
    emptyLabel: "No gallery items yet.",
    fields: [
      { label: "Title", name: "title", required: true, type: "text" },
      { label: "Category", name: "category", type: "text" },
      { label: "Image alt", name: "alt", required: true, type: "text" },
      { label: "Sort order", name: "sortOrder", type: "number" },
    ],
    href: "/admin/gallery",
    icon: Camera,
    label: "Gallery",
    navLabel: "Gallery",
    newLabel: "New gallery item",
    tableColumns: [
      { key: "title", label: "Image" },
      { key: "category", label: "Category" },
      { key: "alt", label: "Alt text" },
      { key: "sortOrder", label: "Order" },
    ],
  },
  media: {
    collection: "media",
    description: "Manage uploaded files.",
    emptyLabel: "No media yet.",
    fields: [
      { label: "Alt text", name: "alt", required: true, type: "text" },
      { label: "Caption", name: "caption", type: "text" },
      { label: "SEO title", name: "seoTitle", type: "text" },
      { label: "SEO description", name: "seoDescription", rows: 3, type: "textarea" },
      { label: "Credit/source", name: "credit", type: "text" },
      { label: "Usage notes", name: "usageNotes", rows: 4, type: "textarea" },
    ],
    href: "/admin/media",
    icon: FileImage,
    label: "Media Library",
    navLabel: "Media",
    newLabel: "New media",
    tableColumns: [
      { key: "alt", label: "Alt text" },
      { key: "filename", label: "File" },
      { key: "mimeType", label: "Type" },
      { key: "updatedAt", label: "Updated" },
    ],
  },
  "seo-settings": {
    description: "Update site metadata.",
    emptyLabel: "Site settings are unavailable.",
    fields: [
      { label: "Site name", name: "siteName", type: "text" },
      { label: "Company name", name: "companyName", type: "text" },
      { label: "Primary email", name: "primaryEmail", type: "email" },
      { label: "Secondary email", name: "secondaryEmail", type: "email" },
      { label: "Phone", name: "phone", type: "text" },
      { label: "WhatsApp", name: "whatsapp", type: "text" },
      { label: "Address", name: "address", rows: 4, type: "textarea" },
      { label: "Trustindex heading", name: "reviewHeading", type: "text" },
      { label: "Trustindex embed code", name: "trustindexEmbed", rows: 6, type: "textarea" },
    ],
    global: "site-settings",
    href: "/admin/seo-settings",
    icon: Settings,
    label: "SEO / Site Settings",
    navLabel: "SEO",
    tableColumns: [],
  },
  "flight-settings": {
    description: "Manage flight affiliate links.",
    emptyLabel: "Flight settings are unavailable.",
    fields: [
      { label: "Provider", name: "provider", options: [
        { label: "Disabled", value: "disabled" },
        { label: "Travelpayouts", value: "travelpayouts" },
        { label: "Skyscanner", value: "skyscanner" },
      ], type: "select" },
      { label: "CTA label", name: "ctaLabel", type: "text" },
      { label: "Affiliate URL", name: "affiliateUrl", type: "url" },
      { label: "Tracking params", name: "trackingParams", type: "text" },
      { label: "Notes", name: "notes", rows: 4, type: "textarea" },
    ],
    global: "flight-affiliate-settings",
    href: "/admin/flight-settings",
    icon: Plane,
    label: "Flight Affiliate",
    navLabel: "Flight Affiliate",
    tableColumns: [],
  },
};

export const sidebarGroups: SidebarGroup[] = [
  {
    defaultOpen: true,
    icon: LayoutDashboard,
    label: "Overview",
    links: [{ href: "/admin", icon: LayoutDashboard, label: "Overview" }],
  },
  {
    defaultOpen: true,
    icon: Tags,
    label: "Trips",
    links: [
      { href: "/admin/trips", icon: Tags, label: "All Trips" },
      { href: "/admin/trips/new", icon: FilePlus2, label: "New Trip" },
      { href: "/admin/destinations", icon: MapPinned, label: "Destinations" },
      { href: "/admin/packages", icon: PackagePlus, label: "Packages" },
    ],
  },
  {
    defaultOpen: true,
    icon: Newspaper,
    label: "Articles",
    links: [
      { href: "/admin/posts", icon: Newspaper, label: "All Articles" },
      { href: "/admin/posts/new", icon: FilePlus2, label: "New Article" },
      { href: "/admin/post-categories", icon: FileText, label: "Categories" },
      { href: "/admin/post-categories/new", icon: FilePlus2, label: "New Category" },
      { href: "/admin/article-tags", icon: Tags, label: "Tags" },
      { href: "/admin/posts-trash", icon: Trash2, label: "Trash" },
    ],
  },
  {
    defaultOpen: true,
    icon: Images,
    label: "Media",
    links: [
      { href: "/admin/media", icon: FileImage, label: "Media Library" },
      { href: "/admin/gallery", icon: Camera, label: "Gallery" },
    ],
  },
  {
    defaultOpen: true,
    icon: Inbox,
    label: "Sales",
    links: [
      { href: "/admin/enquiries", icon: Inbox, label: "Enquiries" },
      { href: "/admin/bookings", icon: CalendarCheck, label: "Bookings" },
      { href: "/admin/accommodations", icon: BedDouble, label: "Stays" },
    ],
  },
  {
    icon: Settings,
    label: "Website",
    links: [
      { href: "/admin/navigation", icon: ListTree, label: "Navigation" },
      { href: "/admin/seo-settings", icon: Globe2, label: "SEO" },
      { href: "/admin/flight-settings", icon: Plane, label: "Flight Affiliate" },
    ],
  },
];

export const sidebarItems = sidebarGroups.flatMap((group) => group.links);

export const notificationLink: SidebarLink = {
  href: "/admin/enquiries",
  icon: Bell,
  label: "Notifications",
};

export function getPortalModule(slug: string) {
  return portalModules[slug];
}
